Models/Meeting.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Meeting_Minutes.Models
{   [Serializable]
    public class Meeting
    {   [Key]
        public int Id { get; set; } // The primary key of the meeting
        [Required]
        [Display(Name = "Date Created")]
        public DateTime CreatedDate { get; set; } = DateTime.Now; //The date when the record was created

        //The full name of the user that created the meeting.
        /*CreatedBy must be a Foreign Key to Users table
        */

       
        [Display(Name ="Organizer")]
        public string CreatedBy { get; set; }
        //[ForeignKey("CreatedBy")]
       // public virtual User User { get; set; }


        // The date when the record was updated
        //When the record is first inserted, it must have the same value as DateCreated
        
        [Display(Name ="Last Updated")]
        public DateTime DateUpdated { get; set; }

        [Required]
        [Display(Name = "Meeting Date")]
        public DateTime MeetingDate { get; set; } // The date and time when the meeting will take place

        /*A status indicating the state of the 
        meeting.The transitions are New → Started → Finished / Cancelled.A “Finished” or 
        “Cancelled” meeting cannot revert to the “New” or “Started” state */
        public MeetingStatus Status { get; set; }


        [Required]
        public string Title { get; set; }  //The title of the meeting  

        [Required]
        [Display(Name = "Participants")]
        public string Participants { get; set; } // A comma-separated string, keeping the mails of external(not registered in the system) participants.
    }
}

Controllers/MeetingsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Meeting_Minutes.Data;
using Meeting_Minutes.Models;
using Microsoft.AspNetCore.Authorization;
using Meeting_Minutes.Services.IServices;
using MimeKit;
using System.Text;

namespace Meeting_Minutes.Controllers
{
   
    [Authorize]
    public class MeetingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IMailService _mailService;

        public MeetingsController(ApplicationDbContext context, IMailService mailservice)
        {
            _context = context;
            _mailService = mailservice;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Meetings.ToListAsync());
        }

        public FileResult DownloadiCal(int? id)
        {
            //Calendar MeetingItems
            var meetingItems = _context.MeetingItems.FirstOrDefault(i => i.Id == id);
        
            StringBuilder sb = new StringBuilder();
            string DateFormat = "yyyyMMddTHHmmssZ";
            string now = DateTime.Now.ToUniversalTime().ToString(DateFormat);
            sb.AppendLine("BEGIN:VCALENDAR");
            sb.AppendLine("PRODID:-//Compnay Inc//Product Application//EN");
            sb.AppendLine("VERSION:2.0");
            sb.AppendLine("METHOD:PUBLISH");
            DateTime dtEnd = Convert.ToDateTime(meetingItems.Deadline);
            sb.AppendLine("BEGIN:VEVENT");
            sb.AppendLine("DTEND:" + dtEnd.ToUniversalTime().ToString(DateFormat));
            sb.AppendLine("DTSTAMP:" + now);
            sb.AppendLine("UID:" + Guid.NewGuid());
            sb.AppendLine("CREATED:" + now);
            sb.AppendLine("LAST-MODIFIED:" + now);
            sb.AppendLine("SEQUENCE:0");
            sb.AppendLine("SUMMARY:" + meetingItems.Description);
            sb.AppendLine("TRANSP:OPAQUE");
            sb.AppendLine("END:VEVENT");
            sb.AppendLine("END:VCALENDAR");
            var calendarBytes = Encoding.UTF8.GetBytes(sb.ToString());
            return File(calendarBytes, "text/calendar", "event.ics");
        }

        public FileResult MeetingCal(int? id)
        {
            //Calendar Meeting
            var meeting = _context.Meetings.FirstOrDefault(i => i.Id == id);

            StringBuilder sb = new StringBuilder();
            string DateFormat = "yyyyMMddTHHmmssZ";
            string now = DateTime.Now.ToUniversalTime().ToString(DateFormat);
            sb.AppendLine("BEGIN:VCALENDAR");
            sb.AppendLine("PRODID:-//Compnay Inc//Product Application//EN");
            sb.AppendLine("VERSION:2.0");
            sb.AppendLine("METHOD:PUBLISH");
            DateTime dtStart = Convert.ToDateTime(meeting.MeetingDate);
            sb.AppendLine("BEGIN:VEVENT");
            sb.AppendLine("DTSTART:" + dtStart.ToUniversalTime().ToString(DateFormat));
            sb.AppendLine("DTSTAMP:" + now);
            sb.AppendLine("UID:" + Guid.NewGuid());
            sb.AppendLine("CREATED:" + now);
            sb.AppendLine("LAST-MODIFIED:" + now);
            sb.AppendLine("SEQUENCE:0");
            sb.AppendLine("SUMMARY:" + meeting.Title);
            sb.AppendLine("TRANSP:OPAQUE");
            sb.AppendLine("END:VEVENT");
            sb.AppendLine("END:VCALENDAR");
            var calendarBytes = Encoding.UTF8.GetBytes(sb.ToString());
            return File(calendarBytes, "text/calendar", "event.ics");
        }



        // POST: Meetings/ShowSearchResults
        [HttpPost]
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase, DateTime? dateFrom, DateTime? dateTo)
        {
            if (!String.IsNullOrEmpty(SearchPhrase) && dateFrom.HasValue && dateTo.HasValue)
            {   
               
                var meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo.Value.AddDays(1)).ToListAsync();
                meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                return View("Index", meetings);// await _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo && j.Title == SearchPhrase).ToListAsync());

            }
            else if (String.IsNullOrEmpty(SearchPhrase) && dateFrom.HasValue && dateTo.HasValue)
            {
                var meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo.Value.AddDays(1)).ToListAsync();
                return View("Index", meetings);
            }
            else if (!String.IsNullOrEmpty(SearchPhrase) && (dateFrom.HasValue || dateTo.HasValue))
            {
                if (dateFrom.HasValue)
                {
                    var meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateFrom).ToListAsync();
                    meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                    return View("Index", meetings);

                }
                else
                {
                    var meetings = await _context.Meetings.Where(j => j.MeetingDate <= dateTo.Value.AddDays(1)).ToListAsync();
                    meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                    return View("Index", meetings);

                }
            }
            else if (dateFrom.HasValue)
            {
                return View("Index", await _context.Meetings.Where(j => j.MeetingDate >= dateFrom).ToListAsync());

            }
            else if (dateTo.HasValue)
            {
                return View("Index", await _context.Meetings.Where(j => j.MeetingDate <= dateTo.Value.AddDays(1)).ToListAsync());

            }
            else
            {
                var meetings = _context.Meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                return View("Index", meetings);
            }
        }



        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }
            var meetingItems = await _context.MeetingItems
            .Where(i => i.MeetingId == id).ToListAsync();
            ViewBag.Risks= _context.ListValues.Where(x => x.ListTypeID == 1).Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Value
            }).ToList();
            var model = new MeetingItemsViewModel
            {
                Meeting = meeting,
                meetingItems = meetingItems
            };
            return View(model);
        }

        // GET: Meetings/Create
        public IActionResult Create()
        {
            ViewBag.User = HttpContext.User.Identity.Name;
            ViewBag.DateCreated = DateTime.Now;

            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string title, DateTime meetingDate, string participants)//([Bind("Id,CreatedDate,CreatedBy,DateUpdated,MeetingDate,Title,Participants")] Meeting meeting)
        {
            if (!string.IsNullOrEmpty(title) && !string.IsNullOrEmpty(participants) && meetingDate != null )
            {
                var meeting = new Meeting();

                meeting.CreatedDate = DateTime.Now;
                meeting.CreatedBy = HttpContext.User.Identity.Name;
                meeting.Title = title;
                meeting.Participants = participants;
                meeting.MeetingDate = meetingDate;

                _context.Add(meeting);
                await _context.SaveChangesAsync();
                
                TempData["success"] = "Meeting created successfully";
                return RedirectToAction(nameof(Index));

            }
            return View(nameof(Index)); //(meeting);
        }

        // GET: Meetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings.FindAsync(id);
            if (meeting == null)
            {
                return NotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CreatedDate,CreatedBy,DateUpdated,MeetingDate,Status,Title,Participants")] Meeting meeting)
        {
            if (id != meeting.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    meeting.DateUpdated = DateTime.Now;
                    
                    _context.Update(meeting);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingExists(meeting.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;

Views/Meetings/Create.cshtml
@model Meeting_Minutes.Models.Meeting

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = ViewBag.User;
    var date = ViewBag.DateCreated;
}

<h1>Create</h1>

<h4>Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input disabled placeholder="@date" class="form-control" />                     @*asp-for="CreatedDate"*@
                @*<span asp-validation-for="CreatedDate" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input  readonly placeholder="@user" class="form-control" />                                        @*asp-for="CreatedBy"*@
                @*<span asp-validation-for="CreatedBy" class="text-danger"></span>*@
            </div>
            @*<div class="form-group">
                <label asp-for="DateUpdated" class="control-label"></label>
                <input asp-for="DateUpdated" class="form-control" />
                <span asp-validation-for="DateUpdated" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Participants" class="control-label"></label>
                <input asp-for="Participants" class="form-control" />
                <span asp-validation-for="Participants" class="text-danger"></span>
            </div>
            <div class="form-group">
               <a type="button" class="btn btn-primary" asp-action="Index"><i class="bi bi-backspace"> Back to List</i></a>

                <input type="submit" value="Create" class="btn btn-success" />

            </div>
        </form>
    </div>
</div>

<div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Meetings/Delete.cshtml
@model Meeting_Minutes.Models.Meeting

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Participants)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Participants)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Meetings/Details.cshtml
@using Meeting_Minutes.Controllers
@model Meeting_Minutes.Models.MeetingItemsViewModel

@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.DateUpdated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.DateUpdated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.MeetingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.MeetingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meeting.Participants)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meeting.Participants)
        </dd>
    </dl>
</div>

<div>
 <a type="button" class="btn btn-primary" asp-action="Index"><i class="bi bi-backspace"> Back to List</i></a>|

<a type="button" class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Meeting?.Id"><i class="bi bi-pencil-square">Edit</i></a>|


   <a type="button" class="btn btn-primary" asp-action="DownloadCSV" asp-route-id="@Model.Meeting.Id" asp-controller="Meetings"><i class="bi bi-file-earmark-excel"> Download CSV</i></a>
	

</div>
<div class="text-end">
    @*<button class="btn btn-success" asp-action="Create" asp-route-id="@Model.Meeting.Id" asp-controller="MeetingItems"> Add New Meeting Item  </button>*@
@*<button class="btn btn-success" asp-action="SendMail" asp-route-id="@Model.Meeting.Id" asp-controller="Meetings"> SendMailButtonPleasePressMe  </button>
*@

<a type="button" class="btn btn-success" asp-action="Create" asp-route-id="@Model.Meeting.Id" asp-controller="MeetingItems"><i class="bi bi-plus-circle-dotted"> Add New Meeting Item</i></a>
	


    @if(@Model.Meeting.Status == MeetingStatus.Started)
    {
        <a type="button" class="btn btn-primary" asp-action="SendMail" asp-route-id="@Model.Meeting.Id" asp-controller="Meetings"> <i class="bi bi-envelope"> End Meeting & SendMail</i> </a>
        @*<a asp-action="SendMail" asp-route-id="@Model.Meeting.Id" asp-controller="Meetings"> End Meeting & Send Mails </a>*@
    }

@*<a asp-action="SendMail" asp-route-id="@Model.Meeting.Id" asp-controller="Meetings"> SendMailButtonPleasePressMe </a>*@

	@*<p>
		<a asp-action="Create" asp-route-id="@Model.Meeting.Id" asp-controller="MeetingItems"> Add New Meeting Item </a>
		</p>*@
</div>


<table class="table">
	<thead>
		<tr>
			<th>
				Description @*@Html.DisplayNameFor(model => meetingItem.Description)*@
			</th>
			<th>
				Deadline @*@Html.DisplayNameFor(model => meetingItem.Deadline)*@
			</th>
			<th>
				Assigned To @*@Html.DisplayNameFor(model => meetingItem.AssignedTo)*@
			</th>
			<th>
				Risk Level @*@Html.DisplayNameFor(model => meetingItem.RiskLevel)*@
			</th>
			<th>
				Requested By  @*@Html.DisplayNameFor(model => meetingItem.RequestedBy)*@
			</th>
			<th>
				Change Requestsd @*@Html.DisplayNameFor(model => meetingItem.ChangeRequested)*@
			</th>
			<th>
				Visible In Minutes @*@Html.DisplayNameFor(model => meetingItem.VisibleInMinutes)*@
			</th>
			<th>
				File Attachment @*@Html.DisplayNameFor(model => meetingItem.FileAttachment)*@
			</th>
			
			
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var meetingItem in Model.meetingItems)
		{
			<tr>

                <td>
                    @Html.DisplayFor(modelItem => meetingItem.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.Deadline)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.AssignedTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.RiskLevel)
                    @*var description = EnumHelper<UserPromotion>.GetDisplayValue(value);
            <li>@Html.DisplayFor(e => description )</li>
             }*@
                 @*   @{HelperFunctions.RiskLevelText(meetingItem.RiskLevel);}*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.RequestedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.ChangeRequested)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => meetingItem.VisibleInMinutes)
                </td>
                <td>

					@if (String.IsNullOrEmpty(meetingItem.FileAttachment))
					{
						<a href="@Html.DisplayFor(modelItem => meetingItem.FileAttachment)"></a>
					}
					else
					{
						@*<a href="@meetingItem.FileAttachment.ToString()" target=_blank download >link</a>*@
                        <a href="~/files/@meetingItem.FileAttachment.ToString()" target=_blank download >link</a>
					}
                    @*Html.ActionLink("Download", "DownloadFile", new { Name = "download.txt" }) *@
					@*<a href="@Html.DisplayFor(modelItem => meetingItem.FileAttachment)">link</a>*@
				</td>
				
				
				<td>
@*					<a asp-action="DownloadiCal" asp-route-id="@meetingItem.Id">Save .ics</a>
*@                    <a type="button" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Download Calendar File" asp-action="DownloadiCal" asp-route-id="@meetingItem.Id"><i class="bi bi-file-earmark-arrow-down"></i></a>

				</td>
				@*
					<td>
					<a asp-action="Edit" asp-route-id="@meetingItem.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@meetingItem.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@meetingItem.Id">Delete</a>
					</td>*@
			</tr>
		}
	</tbody>
</table>

Views/Meetings/Details_old.cshtml
@model Meeting_Minutes.Models.Meeting

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Participants)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Participants)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Meetings/Edit.cshtml
@model Meeting_Minutes.Models.Meeting

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateUpdated" class="control-label"></label>
                <input asp-for="DateUpdated" class="form-control" />
                <span asp-validation-for="DateUpdated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Participants" class="control-label"></label>
                <input asp-for="Participants" class="form-control" />
                <span asp-validation-for="Participants" class="text-danger"></span>
            </div>
            <div class="form-group">
                   <a type="button" class="btn btn-primary" asp-action="Index"><i class="bi bi-backspace"> Back to List</i></a>

                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}