Controllers/UpcomingController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Meeting_Minutes.Data;
using Meeting_Minutes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Session;
using Newtonsoft.Json;

namespace Meeting_Minutes.Controllers
{
    [Authorize]
    public class UpcomingController : Controller
    {
        private readonly ApplicationDbContext _context;
    

        public UpcomingController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var upcomings = _context.Meetings.Where(u => u.MeetingDate > DateTime.Now).ToList();
            return View(upcomings);
        }

        // POST: Meetings/ShowSearchResults
        [HttpPost]
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase, DateTime? dateFrom, DateTime? dateTo)
        {   
            
            if (!String.IsNullOrEmpty(SearchPhrase) && dateFrom.HasValue && dateTo.HasValue)
            {
                List<Meeting> meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo).ToListAsync();
                meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                return View("Index", meetings);// await _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo && j.Title == SearchPhrase).ToListAsync());

            }
            else if (String.IsNullOrEmpty(SearchPhrase) && dateFrom.HasValue && dateTo.HasValue)
            {
                List<Meeting> meetings = _context.Meetings.Where(j => j.MeetingDate >= dateFrom && j.MeetingDate <= dateTo).ToList();
                HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                return View("Index", meetings);
                
            }
            else if (!String.IsNullOrEmpty(SearchPhrase) && (dateFrom.HasValue || dateTo.HasValue))
            {
                if (dateFrom.HasValue)
                {
                    List<Meeting> meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateFrom).ToListAsync();
                    HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                    meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                    return View("Index", meetings);

                }
                else
                {
                    List<Meeting> meetings = await _context.Meetings.Where(j => j.MeetingDate <= dateTo).ToListAsync();
                    HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                    meetings = meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                    return View("Index", meetings);

                }
            }
            else if (dateFrom.HasValue)
            {
                List<Meeting> meetings = await _context.Meetings.Where(j => j.MeetingDate >= dateTo).ToListAsync();
                HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                return View("Index", meetings);

            }
            else if (dateTo.HasValue)
            {
                List<Meeting> meetings = await _context.Meetings.Where(j => j.MeetingDate <= dateTo).ToListAsync();
                HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                return View("Index", meetings);

            }
            else
            {
                List<Meeting> meetings = _context.Meetings.Where(m => m.Title.Contains(SearchPhrase)).ToList();
                HttpContext.Session.SetString("CurrentMeetings", JsonConvert.SerializeObject(meetings));
                return View("Index", meetings);
            }
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }
            //var meetingItems = await _context.MeetingItems
            //.Where(i => i.MeetingId == id).ToListAsync();
            //var model = new Meeting
            //{
            //    Meeting = meeting,
            //    meetingItems = meetingItems
            //};
            return View(meeting);
        }
        public FileContentResult DownloadCSVUpcoming()
        {
            var value = HttpContext.Session.GetString("CurrentMeetings"); 
            List<Meeting> meetingsList = JsonConvert.DeserializeObject<List<Meeting>>(value);

            string csv = "MeetingDate,Title,Status,CreatedBy,CreatedDate,Participants,DateUpdated\n";

            var temp = String.Empty;

         
            //var meetingItemList = _context.MeetingItems.Where(m => m.MeetingId == id).ToList();

            foreach (var element in meetingsList)
            {

                temp = element.MeetingDate.ToString();
                csv = csv + temp;
                temp = element.Title;
                csv = csv + "," + temp;
                temp = element.Status.ToString();
                csv = csv + "," + temp;
                temp = element.CreatedBy;
                csv = csv + temp;
                temp = element.CreatedDate.ToString();
                csv = csv + "," + temp;
                temp = element.Participants;
                csv = csv + "," + temp;
                temp = element.DateUpdated.ToString();
                csv = csv + "," + temp;
                csv = csv + "\n";

            }


            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "UpcomingMeetingsReport.csv");
        }
        
    }


}

Views/Upcoming/Details.cshtml
@model Meeting_Minutes.Models.Meeting

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Participants)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Participants)
        </dd>
    </dl>
</div>
<div>
               <a type="button" class="btn btn-primary" asp-action="Index"><i class="bi bi-backspace"> Back to List</i></a>
</div>

Views/Upcoming/Index.cshtml
@model IEnumerable<Meeting_Minutes.Models.Meeting>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}

<h1>Upcoming Meetings</h1>
<div class="container text-end">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" placeholder="Meeting Title" />
            </div>


            <br />
     
            <div class="form-group">

                <label for="dateFrom" class="control-label">From:</label>
                <input type="date" class="form-control" name="dateFrom">
                <label for="dateTo" class="control-label">to:</label>

                <input type="date" class="form-control" name="dateTo">
            </div>
           
            <div class="form-group">
                <label for="#" class="control-label"></label>
                <input name="#" class="form-control" placeholder="Participants"/>
            </div>
             <br />
                                 <a type="button" class="btn btn-primary " asp-action="DownloadCSVUpcoming"  asp-controller="Upcoming"><i class="bi bi-file-earmark-excel">Download CSV</i></a>

            
          
                              |  <button type="submit" class="btn btn-primary"><i class="bi bi-search"> Search</i> </button>

             </form>


         
    </div>
    
</div>
@*<p class="text-end">
    <a type="button" class="btn btn-success" asp-action="Create"> <i class="bi bi-plus-circle"> Create New</i></a>

  
</p>*@


@*<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="DownloadCSVUpcoming"  asp-controller="Upcoming">Download CSV</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateUpdated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeetingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Participants)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Participants)
            </td>
            <td>
                   <a type="button" class="btn btn-primary btn-sm"asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-info-circle"> Details</i></a>
            </td>
        </tr>
}
    </tbody>
</table>
<p class="text-end">

  
</p>